import store from './storeSetup'

export * from './storeSetup'
export * from './slices/auth'
export * from './slices/base'
export * from './slices/currency'
export * from './slices/tag'
export * from './slices/att-package'
export * from './slices/category'
export * from './slices/subCategory'
export * from './slices/locale/localeSlice'
export * from './slices/brand/brandSlice'
export * from './rootReducer'
export * from './hook'
export default store
