export const API_ENDPOINTS = {
    LOGIN: "/v1/auth/login",
    S3_UPLOAD:'/v1/s3/key',
    S3:'/v1/s3/',
    PRODUCT_IN_STOCK:'/v1/product/in-stock',
    PRODUCT:'/v1/product',
    PRODUCT_SOLD:'/v1/product/out-stock',
    PRODUCT_OUT_EXP:'/v1/product/out-exp',
    PRODUCT_NEW:'/v1/product/new',
    PRODUCT_NON_EXP:'/v1/product/non-exp',
    PRODUCT_SEARCH_NAME:'/v1/product/search-by-name',
    PRODUCT_DETAIL:'/v1/product/product-detail',
    REPORT_TOTAL_PRODUCT: '/v1/report/report-quanity-product',
    EXCHANGE:'/v1/exchange/today',
    EXCHANGE_DATE:'/v1/exchange/date',
    //ver-java
    SUPPLIER:'/v1/supplier/all-supplier',
    CREATE_SHIPPING_PRICE:'/v1/shipping-price-pallet/create',
    CREATE_CIF_PRICE:'/v1/price-cif/create-cif',
    PRODUCT_ALL:'/v1/product/all-product',
    PRODUCT_ALL_CIF:'/v1/price-cif/all-cif',
  };